ALTER TABLE staff ADD COLUMN salary float8 NOT NULL DEFAULT 50000;
ALTER TABLE seller ADD COLUMN percentageOfSales float8 NOT NULL DEFAULT 10;
ALTER TABLE storekeeper ADD COLUMN bonus float8 NOT NULL DEFAULT 20;
